# .project metadata for Rook
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

schema_version: "1.0.0"
slug: "rook"
name: "Rook"
description: "Storage Orchestration for Kubernetes"
type: "project"
project_lead: "travisn"
slack_channels:
  - name: "#general"
    link: "https://slack.rook.io"
    primary: true
  - name: "#announcements"
  - name: "#ceph"
  - name: "#ceph-csi"
  - name: "#conferences"

maturity_log:
  - phase: "graduated"
    date: "2020-10-07T00:00:00Z"
    issue: "https://github.com/cncf/toc/pull/366"

repositories:
  - url: "https://github.com/rook/rook"
    primary: true

website: "https://rook.io/"

artwork: "https://github.com/rook/artwork"

adopters:
  path: "https://github.com/rook/rook/blob/master/ADOPTERS.md"

package_managers:
  docker: "rook/rook"
  ghcr: "rook/rook-ceph"

social:
  twitter: "https://twitter.com/rook_io"

security:
  policy:
    path: "https://github.com/rook/rook/blob/master/SECURITY.md"
  contact:
    advisory_url: "https://github.com/rook/rook/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/rook/rook/blob/master/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/rook/rook/blob/master/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/rook/rook/blob/master/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://rook.io/docs/rook/latest-release/Getting-Started/intro/"

landscape:
  category: "Runtime"
  subcategory: "Cloud Native Storage"

# CLOMonitor Score: 92/100
# Documentation: 97 | License: 100 | Best Practices: 95 | Security: 73
